# Generated by Django 4.2 on 2024-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_Title', models.CharField(max_length=20)),
                ('section_Title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('vision', models.CharField(max_length=400)),
            ],
        ),
    ]
