# Generated by Django 4.2 on 2024-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0002_core_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_values',
            name='SI_No',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
