# Generated by Django 4.2 on 2024-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_Name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('year', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('abn', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
