# Generated by Django 4.2 on 2024-06-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0002_alter_setting_favicon_alter_setting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='consultency',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
