# Generated by Django 4.2 on 2024-06-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0004_setting_email_setting_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_Map_link',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
