# Generated by Django 4.2 on 2024-06-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0005_setting_google_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='google_Map_link',
            new_name='google_Map_Link',
        ),
    ]
