# Generated by Django 4.2 on 2024-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0006_rename_google_map_link_setting_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='flash_News',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
