# Generated by Django 4.2 on 2024-06-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0008_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='error_Image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
