# Generated by Django 4.2 on 2024-06-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0009_background_error_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='about_Page_Banner',
            field=models.FileField(upload_to='background/'),
        ),
    ]
