# Generated by Django 4.2 on 2024-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0010_alter_background_about_page_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo_2',
            field=models.FileField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
