# Generated by Django 4.2 on 2024-07-13 06:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insights_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('cover_photo', models.ImageField(upload_to='insights/')),
                ('author', models.CharField(max_length=50)),
                ('author_profile', models.ImageField(upload_to='insights/author/')),
                ('desc', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insights_Page.insightscategory')),
            ],
        ),
    ]
