# Generated by Django 4.2 on 2024-06-26 06:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0003_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', models.FileField(upload_to='icon/')),
                ('description', models.TextField()),
                ('serve', models.TextField()),
                ('long_Description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
