# Generated by Django 4.2 on 2024-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.FileField(default=1, upload_to='service/'),
            preserve_default=False,
        ),
    ]
