# Generated by Django 4.2 on 2024-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0006_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_Name', models.CharField(max_length=30)),
                ('tech_Pertners', models.IntegerField()),
                ('years_Of_Experience', models.IntegerField()),
                ('professionals', models.IntegerField()),
                ('complete_Projects', models.IntegerField()),
            ],
        ),
    ]
