# Generated by Django 4.2 on 2024-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
    ]
