# Generated by Django 4.2 on 2024-07-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0011_alter_product_icon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='logo',
            new_name='icon',
        ),
    ]
