# Generated by Django 4.2 on 2024-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0012_rename_logo_technology_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(upload_to='technology/'),
        ),
    ]
